// ============================================================
// App data — IBM webMethods MFT / IWHI question analytics.
// ============================================================

// Overall (all-time) dashboard: common questions ranked by occurrences.
window.DASHBOARD_DATA = {
  totalQuestions: 136,
  totalGroups: 10,
  resolved: 71,
  topTopic: 'Antivirus scanning',
  groups: [
    { rank: 1, count: 28, similarity: '92%', topic: 'Antivirus scanning',
      question: 'How do I configure virus scanning in MFT and handle scan failures?',
      keywords: ['mft', 'antivirus', 'quarantine', 'notification', 'post-processing'],
      questions: [
        { text: 'Copy Task to target failing: "Exception while scanning for virus".', date: 'Jun 5' },
        { text: 'When a virus is detected, send an email notification to an admin?', date: 'Jun 5' },
        { text: 'Post-processing scanner → move file to quarantine or approved + send mail?', date: 'Jun 2' },
        { text: 'Can a post-processing script return a custom error to drive routing?', date: 'Jun 2' },
      ] },
    { rank: 2, count: 22, similarity: '90%', topic: 'Metering & usage',
      question: 'How can customers measure MFT transaction statistics without the metering server?',
      keywords: ['metering', 'transactions', 'usage', 'entitlements'],
      questions: [
        { text: 'Check own transaction stats (inbound/outbound counts, file sizes)?', date: 'May 30' },
        { text: 'Estimate MFT transactions in the absence of a metering server?', date: 'Jun 2' },
        { text: 'Does the Metering Agent ship pre-installed in the Capabilities Container images?', date: 'Jun 9' },
      ] },
    { rank: 3, count: 19, similarity: '89%', topic: 'Cloud storage connectivity',
      question: 'Azure Blob / cloud storage connectivity and token authorization',
      keywords: ['azure', 'sas-token', 'blob', 'authorization'],
      questions: [
        { text: 'Storage-account token works but Container-level SAS token fails authorization.', date: 'Jun 5' },
        { text: 'Correct IPs, protocols, CRUD permissions — still a Container token auth failure.', date: 'Jun 5' },
      ] },
    { rank: 4, count: 17, similarity: '88%', topic: 'Scheduled Action APIs',
      question: 'Is there a REST API to trigger or deactivate Scheduled Actions?',
      keywords: ['rest-api', 'scheduled-actions', 'automation'],
      questions: [
        { text: 'REST API to deactivate a list of Scheduled and Post-Processing Actions?', date: 'Jun 5' },
        { text: 'Trigger a file transfer via a REST API call instead of a schedule?', date: 'Jun 3' },
      ] },
    { rank: 5, count: 14, similarity: '86%', topic: 'UI errors after upgrade',
      question: 'Internal error / NullPointerException opening the MFT UI after a 12.x install',
      keywords: ['mft-ui', 'upgrade', 'nullpointer', 'error'],
      questions: [
        { text: 'Installed v12, cannot open MFT UI — MFTServiceException internal error.', date: 'Jun 3' },
        { text: 'NullPointerException — Datastore.logger is null while fetching UI settings.', date: 'Jun 3' },
      ] },
    { rank: 6, count: 11, similarity: '84%', topic: 'Control-file triggers',
      question: 'Use a control (.ctrl) file to trigger transfer once the data file is ready',
      keywords: ['find-task', 'control-file', 'trigger'],
      questions: [
        { text: 'On finding {name}.ctrl, move {name}.dat to the destination?', date: 'Jun 5' },
      ] },
    { rank: 7, count: 9, similarity: '83%', topic: 'Monitoring & alerting',
      question: 'IWHI end-to-end monitoring & alerting best practices',
      keywords: ['iwhi', 'monitoring', 'alerting'],
      questions: [
        { text: 'Monitor a single app and alert on the first error — one group per product?', date: 'Jun 9' },
      ] },
    { rank: 8, count: 7, similarity: '81%', topic: 'Thread scaling',
      question: 'Avoiding thread exhaustion with thousands of scheduled actions',
      keywords: ['threads', 'scheduler', 'scaling'],
      questions: [
        { text: '8,600 scheduled actions on a 2-node cluster — how to avoid running out of threads?', date: 'Jun 5' },
      ] },
    { rank: 9, count: 5, similarity: '80%', topic: 'Certificates & key vaults',
      question: 'Integrate the Certificate store with an external key vault (e.g. HashiCorp)',
      keywords: ['certificate', 'key-vault', 'hashicorp'],
      questions: [
        { text: 'Can the platform Certificate store integrate with an external key vault?', date: 'Jun 3' },
      ] },
    { rank: 10, count: 4, similarity: '78%', topic: 'File merge',
      question: 'Merge content of multiple files via a Flow Service',
      keywords: ['flow-service', 'merge', 'files'],
      questions: [
        { text: 'Find file001.txt + file002.txt and merge via a Flow Service?', date: 'Jun 5' },
      ] },
  ],
};

// This-week view (Pulse). 6-week volume trend + ranked + movement.
window.WEEK_DATA = {
  weekLabel: 'Jun 2 – 8, 2026',
  totalThisWeek: 22,
  totalLastWeek: 18,
  deltaPct: +18,
  newQuestionTypes: 5,
  groupsThisWeek: 8,
  answered: 3,
  trend: [14, 12, 19, 16, 18, 22],
  trendLabels: ['May 5', 'May 12', 'May 19', 'May 26', 'Jun 1', 'Jun 8'],
  groups: [
    { rank: 1, count: 4, movement: 'new', topic: 'Antivirus scanning',
      question: 'How do I configure virus scanning in MFT and handle failures?',
      keywords: ['mft', 'antivirus', 'quarantine'] },
    { rank: 2, count: 3, movement: 'new', topic: 'Metering & usage',
      question: 'Measuring MFT transaction statistics without the metering server',
      keywords: ['metering', 'transactions', 'usage'] },
    { rank: 3, count: 2, movement: +2, topic: 'Scheduled Action APIs',
      question: 'Is there a REST API to trigger or deactivate Scheduled Actions?',
      keywords: ['rest-api', 'scheduled-actions'] },
    { rank: 4, count: 2, movement: 'new', topic: 'UI errors after upgrade',
      question: 'Internal error / NullPointerException opening MFT UI after 12.x install',
      keywords: ['mft-ui', 'upgrade', 'error'] },
    { rank: 5, count: 1, movement: -1, topic: 'Azure Blob auth',
      question: 'Azure Blob Container-level SAS token authorization failure',
      keywords: ['azure', 'sas-token'] },
    { rank: 6, count: 1, movement: 'new', topic: 'Control-file triggers',
      question: 'Use a control (.ctrl) file to trigger transfer when data is ready',
      keywords: ['find-task', 'control-file'] },
    { rank: 7, count: 1, movement: -3, topic: 'Monitoring & alerting',
      question: 'IWHI end-to-end monitoring & alerting best practices',
      keywords: ['iwhi', 'monitoring'] },
    { rank: 8, count: 1, movement: +1, topic: 'Thread scaling',
      question: 'Avoiding thread exhaustion with thousands of scheduled actions',
      keywords: ['threads', 'scheduler'] },
  ],
};
